services:
  web:
    env_file: .env
    environment:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    ports: 
      - "8000:8000"
    # remove at prod
    volumes: 
      - .:/app 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    command: celery -A config worker --loglevel=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:14.6-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # persist data to disk
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  piston:
    image: ghcr.io/engineer-man/piston:latest
    privileged: true        # required for isolate sandboxing
    restart: always
    volumes:
      - piston_data:/piston/data

volumes:
  piston_data:            
  postgres_data:
  redis_data:
  rabbitmq_data:

      