# Generated by Django 6.0.2 on 2026-03-15 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lessons", "0002_alter_choiceoption_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("C", "Correct"), ("W", "Wrong")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="lessons.step",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submissions_submission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_code", models.TextField()),
                ("tests_passed", models.PositiveSmallIntegerField(default=0)),
                ("tests_total", models.PositiveSmallIntegerField(default=0)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_submission",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_codesubmissions",
            },
        ),
        migrations.CreateModel(
            name="ChoiceSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_option_ids", models.JSONField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choice_submission",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_choicesubmissions",
            },
        ),
        migrations.CreateModel(
            name="TestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("actual_output", models.TextField()),
                ("runtime_ms", models.PositiveSmallIntegerField(default=0)),
                ("memory_mb", models.PositiveSmallIntegerField(default=0)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="submissions.codesubmission",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="lessons.testcase",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_testcasesubmissions",
                "ordering": ["test_case__order"],
            },
        ),
        migrations.CreateModel(
            name="TextSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_submission",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_textsubmissions",
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["user", "step"], name="submissions_user_id_d0dc56_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testcaseresult",
            unique_together={("submission", "test_case")},
        ),
    ]
