# Generated by Django 6.0.2 on 2026-04-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_choiceoption_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
