# Generated by Django 6.0.2 on 2026-04-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
